name: Package

on: workflow_dispatch

jobs:
  package:
    name: Create war
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: mvnw package
        run: ./mvnw package
